#!/bin/bash

function state {
  echo $1 > ~/bin/pomodoro.state
}

function log {
  echo "$1 `date`" >> ~/pomodoro.log
}

function beepbeep {
   beep -f 65.4064 -l 100 -n -f 130.813 -l 100 -n -f 261.626 -l 100 -n -f 523.251 -l 100 -n -f 1046.50 -l 100 -n -f 2093.00 -l 100 -n -f 4186.01 -l 100
}

function notify {
  beepbeep
  notify-send Pomodoro "$1" -t 60
}

 #[25,5,25,5,25,5,25,15]

notify "First 25"
log "Start"

while true; do
	for i in {1..3} ; do
		state "25"
		sleep 25m
		state "5"
		notify "25 minutes elapses, take a break" 
		log "Work 25"
		sleep 5m
		notify "5 minute break over take back to work" 
		log "Break 5"
	done

	state "25"
	sleep 25m
	notify "25 minutes elapses, take a  long break" 
	log "Work 25"

	state "15"
	sleep 15m
	notify "15 minute break over take back to work" 
	log "Break 15"
done

